import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useChecklistFields } from "@/hooks/useChecklistFields";
import { getTemplate } from "@/lib/checklistTemplates";
import { mergeExtractedFields, type ExtractedField } from "@/lib/checklistMerge";
import { useRole } from "@/hooks/useRole";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Phone,
  PhoneOff,
  Sparkles,
  RefreshCw,
  Loader2,
  ListChecks,
  Mic,
  ChevronRight,
  CheckCircle2,
  AlertCircle,
  FileText,
  PlayCircle,
  Clock,
} from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";

interface Props {
  caseId: string;
  planType: string;
  clientName: string;
  providerName: string;
  planNumber: string;
}

interface CallScript {
  opener: string;
  sections: Array<{
    title: string;
    questions: Array<{ field_key: string; question: string; purpose: "obtain" | "verify" }>;
  }>;
  objection_handlers: Array<{ objection: string; response: string }>;
  closing: string;
}

interface ExtractedItem {
  key: string;
  value: string | null;
  confidence: "HIGH" | "MEDIUM" | "LOW" | "MISSING";
  evidence_quote: string;
  reasoning?: string;
}

const SAMPLE_TRANSCRIPT = `[CA — Priya] Good morning, this is Priya Ramesh calling from Furnley House on behalf of our client Eleanor Whitmore regarding plan AV-PP-55021. We have an LOA on file dated 2 April. Can you confirm a few outstanding items please?

[Aviva — Mark] Yes, I can see the LOA. Go ahead.

[CA] Could you confirm the current value of the plan?
[Aviva] As of close of business yesterday, the current value is £127,450.32.

[CA] Thank you. And the transfer value?
[Aviva] Transfer value is the same — £127,450.32. No MVR or penalty applies.

[CA] What's the annual management charge?
[Aviva] AMC is 0.45%. There's no separate platform charge on this plan.

[CA] And the funds held?
[Aviva] It's invested 100% in the Aviva Pension MyM My Future Focus Growth fund.

[CA] What's the selected retirement age on file?
[Aviva] Selected retirement age is 65.

[CA] Are there any safeguarded or guaranteed benefits?
[Aviva] No safeguarded benefits. No GMP, no GAR.

[CA] And expression of wishes?
[Aviva] Yes — completed 12 March 2024, sole beneficiary is the spouse.

[CA] Perfect. I'll get that emailed across. Thank you Mark.`;

export function CallWorkspace({ caseId, planType, clientName, providerName, planNumber }: Props) {
  const { role, userName } = useRole();
  const template = useMemo(() => getTemplate(planType), [planType]);
  const { rows, refresh } = useChecklistFields({ caseId, template });

  const [script, setScript] = useState<CallScript | null>(null);
  const [scriptLoading, setScriptLoading] = useState(false);
  const [scriptError, setScriptError] = useState<string | null>(null);

  const [callActive, setCallActive] = useState(false);
  const [callStartedAt, setCallStartedAt] = useState<number | null>(null);
  const [elapsedSec, setElapsedSec] = useState(0);
  const [transcript, setTranscript] = useState("");

  const [analyzing, setAnalyzing] = useState(false);
  const [reviewOpen, setReviewOpen] = useState(false);
  const [aiSummary, setAiSummary] = useState<string>("");
  const [extractedItems, setExtractedItems] = useState<ExtractedItem[]>([]);
  const [acceptedKeys, setAcceptedKeys] = useState<Set<string>>(new Set());
  const [merging, setMerging] = useState(false);

  const lastAutoGeneratedFor = useRef<string | null>(null);

  // ── Build the missing/review field lists for the script + extraction targets ──
  const labelByKey = useMemo(() => {
    const m = new Map<string, { label: string; section: string; type?: string; hint?: string }>();
    template.forEach((t) => m.set(t.key, { label: t.label, section: t.section, type: t.type, hint: t.hint }));
    return m;
  }, [template]);

  const missingFields = useMemo(
    () =>
      rows
        .filter((r) => r.field_key && (!r.value || r.status === "missing"))
        .map((r) => ({
          key: r.field_key!,
          label: r.label,
          section: r.section,
          hint: labelByKey.get(r.field_key!)?.hint ?? null,
        })),
    [rows, labelByKey],
  );

  const reviewFields = useMemo(
    () =>
      rows
        .filter(
          (r) =>
            r.field_key &&
            r.value &&
            (r.confidence === "LOW" || r.status === "review_requested"),
        )
        .map((r) => ({
          key: r.field_key!,
          label: r.label,
          section: r.section,
          value: r.value,
          confidence: r.confidence ?? "LOW",
        })),
    [rows],
  );

  const totalQuestions = missingFields.length + reviewFields.length;

  // ── Auto-generate script once when fields are loaded ──
  useEffect(() => {
    if (totalQuestions === 0) return;
    const sig = `${caseId}-${missingFields.length}-${reviewFields.length}`;
    if (lastAutoGeneratedFor.current === sig) return;
    lastAutoGeneratedFor.current = sig;
    void generateScript();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [caseId, missingFields.length, reviewFields.length]);

  // ── Call timer ──
  useEffect(() => {
    if (!callActive || !callStartedAt) return;
    const id = window.setInterval(() => {
      setElapsedSec(Math.floor((Date.now() - callStartedAt) / 1000));
    }, 1000);
    return () => window.clearInterval(id);
  }, [callActive, callStartedAt]);

  const generateScript = async () => {
    if (totalQuestions === 0) return;
    setScriptLoading(true);
    setScriptError(null);
    try {
      const { data, error } = await supabase.functions.invoke("generate-script", {
        body: {
          fields: missingFields,
          reviewFields,
          clientName,
          providerName,
          planNumber,
          planType,
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setScript(data.script as CallScript);
    } catch (e: any) {
      const msg = e?.message ?? "Failed to generate script";
      setScriptError(msg);
      if (msg.includes("Rate limit")) {
        toast.error("AI rate-limited", { description: "Please wait a moment and click Regenerate." });
      } else if (msg.toLowerCase().includes("credit")) {
        toast.error("AI credits exhausted", {
          description: "Add credits in Settings → Workspace → Usage.",
        });
      } else {
        toast.error("Script generation failed", { description: msg });
      }
    } finally {
      setScriptLoading(false);
    }
  };

  const handleStartCall = () => {
    setCallActive(true);
    setCallStartedAt(Date.now());
    setElapsedSec(0);
    toast.success("Call started", {
      description: "In production this would dial via RingCentral.",
    });
  };

  const handleEndCall = () => {
    setCallActive(false);
    if (!transcript.trim()) {
      toast.info("Call ended — no transcript captured", {
        description: "Paste a transcript below, then click Analyse.",
      });
    }
  };

  const insertSampleTranscript = () => {
    setTranscript(SAMPLE_TRANSCRIPT);
    toast.info("Sample transcript inserted", {
      description: "In production this would be the Palindrome STT output.",
    });
  };

  // ── End Call → AI Analysis → Review modal ──
  const handleAnalyse = async () => {
    if (!transcript.trim()) {
      toast.error("Add a transcript first");
      return;
    }
    setAnalyzing(true);
    try {
      // Targets = all missing + review fields (so AI knows what to look for)
      const targetSet = new Map<string, { key: string; label: string; section: string; type?: string; hint?: string }>();
      missingFields.forEach((f) =>
        targetSet.set(f.key, { key: f.key, label: f.label, section: f.section, hint: f.hint ?? undefined }),
      );
      reviewFields.forEach((f) =>
        targetSet.set(f.key, { key: f.key, label: f.label, section: f.section }),
      );
      // If there are no obvious missing/review fields, default to all template keys
      if (targetSet.size === 0) {
        template.forEach((t) =>
          targetSet.set(t.key, { key: t.key, label: t.label, section: t.section, type: t.type, hint: t.hint }),
        );
      }
      const targets = Array.from(targetSet.values()).map((t) => ({
        key: t.key,
        label: t.label,
        section: t.section,
        type: labelByKey.get(t.key)?.type ?? "text",
        hint: t.hint,
      }));

      const { data, error } = await supabase.functions.invoke("analyze-transcript", {
        body: {
          mode: "extract",
          transcript,
          targets,
          clientName,
          providerName,
          planNumber,
        },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      const items = ((data?.extracted ?? []) as ExtractedItem[]).filter(
        (it) => it.confidence !== "MISSING" && it.value,
      );
      setExtractedItems(items);
      setAiSummary(data?.summary ?? "");
      // Pre-select all HIGH/MEDIUM by default; LOW left unchecked
      setAcceptedKeys(new Set(items.filter((it) => it.confidence !== "LOW").map((it) => it.key)));
      setReviewOpen(true);
    } catch (e: any) {
      const msg = e?.message ?? "Analysis failed";
      if (msg.includes("Rate limit")) {
        toast.error("AI rate-limited", { description: "Please wait a moment and try again." });
      } else if (msg.toLowerCase().includes("credit")) {
        toast.error("AI credits exhausted", {
          description: "Add credits in Settings → Workspace → Usage.",
        });
      } else {
        toast.error("Analysis failed", { description: msg });
      }
    } finally {
      setAnalyzing(false);
    }
  };

  // ── Save call_log + merge accepted fields into checklist + write audit ──
  const handleConfirmMerge = async () => {
    setMerging(true);
    try {
      const acceptedItems = extractedItems.filter((it) => acceptedKeys.has(it.key));

      // 1. Save call log
      const { data: { user } } = await supabase.auth.getUser();
      const { error: logErr } = await supabase.from("call_logs").insert({
        user_id: user?.id ?? "00000000-0000-0000-0000-000000000000",
        case_id: caseId,
        provider_name: providerName,
        client_name: clientName,
        plan_number: planNumber,
        phone_number: "—", // would come from RingCentral in production
        duration_seconds: elapsedSec || null,
        transcript: transcript.trim(),
        ai_summary: aiSummary || null,
        fields_resolved: acceptedItems.map((it) => it.key),
        notes: `Saved from Stage 5 Call Workspace (${role ?? "unknown role"})`,
        status: "completed",
      });
      if (logErr) console.error("call_logs insert error", logErr);

      // 2. Merge into checklist using the same merge engine as PDF extraction
      const extracted: ExtractedField[] = acceptedItems.map((it) => ({
        key: it.key,
        value: it.value,
        confidence: it.confidence,
        source_page: null,
        source_section: null,
        reasoning: it.reasoning ?? it.evidence_quote,
      }));

      const existingByKey = new Map(
        rows.filter((r) => r.field_key).map((r) => [r.field_key!, r]),
      );
      const templateLookup = new Map(template.map((t) => [t.key, { label: t.label, section: t.section }]));
      const { upserts, skipped } = mergeExtractedFields(extracted, {
        caseId,
        documentName: `Provider call (${new Date().toLocaleString("en-GB")})`,
        templateLookup,
        existingByKey,
      });

      for (const u of upserts) {
        const ex = existingByKey.get(u.field_key);
        const evidence_source = `Provider call · ${providerName}`;
        const evidence_ref =
          extractedItems.find((it) => it.key === u.field_key)?.evidence_quote?.slice(0, 240) ?? null;
        if (ex) {
          await supabase
            .from("checklist_fields")
            .update({
              value: u.value,
              confidence: u.confidence,
              status: u.status,
              source_page: null,
              evidence_source,
              evidence_ref,
              extracted_at: u.extracted_at,
              manually_edited: false,
              notes: u.notes,
            })
            .eq("id", ex.id);
        } else {
          await supabase.from("checklist_fields").insert({
            case_id: u.case_id,
            field_key: u.field_key,
            label: u.label,
            section: u.section,
            value: u.value,
            confidence: u.confidence,
            status: u.status,
            evidence_source,
            evidence_ref,
            extracted_at: u.extracted_at,
            manually_edited: false,
            notes: u.notes,
          });
        }
      }

      if (upserts.length > 0) {
        await supabase.from("field_audit").insert(
          upserts.map((u) => ({
            case_id: caseId,
            field_key: u.field_key,
            field_label: u.label,
            action: "call_extract",
            source: "call",
            old_value: existingByKey.get(u.field_key)?.value ?? null,
            new_value: u.value,
            confidence: u.confidence,
            actor_role: role ?? null,
            actor_name: userName ?? "CA Team",
            notes: extractedItems.find((it) => it.key === u.field_key)?.evidence_quote?.slice(0, 240) ?? null,
          })),
        );
      }

      toast.success(`Merged ${upserts.length} field${upserts.length === 1 ? "" : "s"} from the call`, {
        description:
          skipped.length > 0
            ? `${skipped.length} kept (manual edits / approvals preserved)`
            : "Call logged and checklist updated",
      });

      setReviewOpen(false);
      setExtractedItems([]);
      setAiSummary("");
      setTranscript("");
      setElapsedSec(0);
      setCallStartedAt(null);
      await refresh();
    } catch (e: any) {
      console.error("merge error", e);
      toast.error("Failed to save call results", { description: e?.message ?? "Unknown error" });
    } finally {
      setMerging(false);
    }
  };

  const formatTime = (s: number) => {
    const m = Math.floor(s / 60);
    const r = s % 60;
    return `${m.toString().padStart(2, "0")}:${r.toString().padStart(2, "0")}`;
  };

  return (
    <div className="grid gap-4 lg:grid-cols-[1fr,1.4fr]">
      {/* ─── LEFT: Missing fields summary ─── */}
      <div className="rounded-md border border-border bg-card overflow-hidden">
        <div className="px-3 py-2 border-b border-border bg-muted/40">
          <h4 className="text-[11px] uppercase tracking-widest font-bold text-muted-foreground flex items-center gap-1.5">
            <ListChecks className="h-3.5 w-3.5" />
            Outstanding fields ({totalQuestions})
          </h4>
        </div>
        <div className="p-3 space-y-3 max-h-[520px] overflow-y-auto">
          {totalQuestions === 0 ? (
            <p className="text-xs text-muted-foreground italic text-center py-6">
              No outstanding fields. The checklist is complete — no call needed.
            </p>
          ) : (
            <>
              {missingFields.length > 0 && (
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-overdue font-semibold mb-1.5">
                    Missing ({missingFields.length})
                  </p>
                  <ul className="space-y-1">
                    {missingFields.map((f) => (
                      <li key={f.key} className="text-xs flex items-center gap-1.5">
                        <AlertCircle className="h-3 w-3 text-overdue shrink-0" />
                        <span className="text-foreground">{f.label}</span>
                        <span className="text-muted-foreground">· {f.section}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {reviewFields.length > 0 && (
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-warning font-semibold mb-1.5">
                    To verify ({reviewFields.length})
                  </p>
                  <ul className="space-y-1">
                    {reviewFields.map((f) => (
                      <li key={f.key} className="text-xs flex items-center gap-1.5">
                        <AlertCircle className="h-3 w-3 text-warning shrink-0" />
                        <span className="text-foreground">{f.label}</span>
                        <span className="text-muted-foreground">— "{f.value}"</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          )}
        </div>
      </div>

      {/* ─── RIGHT: AI script + call workspace ─── */}
      <div className="space-y-3">
        {/* Script panel */}
        <div className="rounded-md border border-border bg-card overflow-hidden">
          <div className="px-3 py-2 border-b border-border bg-muted/40 flex items-center justify-between">
            <h4 className="text-[11px] uppercase tracking-widest font-bold text-muted-foreground flex items-center gap-1.5">
              <Sparkles className="h-3.5 w-3.5 text-teal" />
              AI Call Script
            </h4>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs"
              onClick={generateScript}
              disabled={scriptLoading || totalQuestions === 0}
            >
              {scriptLoading ? (
                <Loader2 className="h-3 w-3 animate-spin mr-1" />
              ) : (
                <RefreshCw className="h-3 w-3 mr-1" />
              )}
              Regenerate
            </Button>
          </div>
          <div className="p-3 max-h-[260px] overflow-y-auto text-sm">
            {scriptLoading && !script && (
              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                <Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating tailored script…
              </div>
            )}
            {scriptError && !script && (
              <p className="text-xs text-destructive">{scriptError}</p>
            )}
            {!scriptLoading && !script && !scriptError && totalQuestions === 0 && (
              <p className="text-xs text-muted-foreground italic">
                No questions to ask the provider — checklist is fully resolved.
              </p>
            )}
            {script && (
              <div className="space-y-3">
                {script.opener && (
                  <p className="text-foreground leading-relaxed italic">"{script.opener}"</p>
                )}
                {(script.sections ?? []).map((s, i) => (
                  <div key={i}>
                    <p className="text-[10px] uppercase tracking-wider text-teal font-semibold mb-1">
                      {s.title}
                    </p>
                    <ul className="space-y-1">
                      {(s.questions ?? []).map((q, j) => (
                        <li key={j} className="text-xs flex gap-1.5">
                          <ChevronRight className="h-3 w-3 mt-0.5 shrink-0 text-muted-foreground" />
                          <span className="text-foreground">{q.question}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
                {(script.objection_handlers ?? []).length > 0 && (
                  <details className="text-xs">
                    <summary className="cursor-pointer text-[10px] uppercase tracking-wider text-warning font-semibold">
                      Objection handlers ({script.objection_handlers.length})
                    </summary>
                    <ul className="mt-1 space-y-1.5">
                      {script.objection_handlers.map((o, i) => (
                        <li key={i} className="text-foreground">
                          <span className="font-semibold">"{o.objection}"</span>{" "}
                          → <span className="italic text-muted-foreground">{o.response}</span>
                        </li>
                      ))}
                    </ul>
                  </details>
                )}
                {script.closing && (
                  <p className="text-foreground leading-relaxed italic border-t border-border pt-2">
                    "{script.closing}"
                  </p>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Call controls + transcript */}
        <div className="rounded-md border border-border bg-card overflow-hidden">
          <div className="px-3 py-2 border-b border-border bg-muted/40 flex items-center justify-between">
            <h4 className="text-[11px] uppercase tracking-widest font-bold text-muted-foreground flex items-center gap-1.5">
              <Mic className="h-3.5 w-3.5 text-info" />
              Call & Transcript
            </h4>
            {callActive && (
              <Badge variant="outline" className="bg-overdue/10 text-overdue border-overdue/30">
                <span className="h-1.5 w-1.5 rounded-full bg-overdue mr-1.5 animate-pulse" />
                LIVE · {formatTime(elapsedSec)}
              </Badge>
            )}
            {!callActive && elapsedSec > 0 && (
              <Badge variant="outline">
                <Clock className="h-3 w-3 mr-1" /> {formatTime(elapsedSec)}
              </Badge>
            )}
          </div>
          <div className="p-3 space-y-3">
            <div className="flex flex-wrap gap-2">
              {!callActive ? (
                <Button size="sm" onClick={handleStartCall} disabled={totalQuestions === 0}>
                  <Phone className="h-3.5 w-3.5 mr-1.5" />
                  Start call (RingCentral)
                </Button>
              ) : (
                <Button size="sm" variant="destructive" onClick={handleEndCall}>
                  <PhoneOff className="h-3.5 w-3.5 mr-1.5" />
                  End call
                </Button>
              )}
              <Button size="sm" variant="outline" onClick={insertSampleTranscript}>
                <FileText className="h-3.5 w-3.5 mr-1.5" />
                Insert sample transcript
              </Button>
              <Button
                size="sm"
                variant="default"
                onClick={handleAnalyse}
                disabled={!transcript.trim() || analyzing}
                className="ml-auto bg-teal hover:bg-teal/90"
              >
                {analyzing ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" />
                ) : (
                  <PlayCircle className="h-3.5 w-3.5 mr-1.5" />
                )}
                Analyse & propose updates
              </Button>
            </div>

            <Textarea
              value={transcript}
              onChange={(e) => setTranscript(e.target.value)}
              placeholder="Transcript appears here as the call progresses (Palindrome STT in production).&#10;You can also paste / edit before clicking 'Analyse'."
              className="min-h-[180px] text-xs font-mono"
            />
            <p className="text-[10px] text-muted-foreground italic">
              In production: RingCentral records the call → recording is sent to Palindrome (jargon-aware financial STT) → transcript is dropped here automatically.
            </p>
          </div>
        </div>
      </div>

      {/* ─── Review & merge modal ─── */}
      <Dialog open={reviewOpen} onOpenChange={setReviewOpen}>
        <DialogContent className="max-w-2xl max-h-[85vh] overflow-hidden flex flex-col">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-teal" />
              AI extracted {extractedItems.length} field
              {extractedItems.length === 1 ? "" : "s"} from the call
            </DialogTitle>
            <DialogDescription>
              Tick the values you want to merge into the checklist. Manually edited and approved
              fields will be preserved automatically.
            </DialogDescription>
          </DialogHeader>

          <div className="flex-1 overflow-y-auto space-y-3 pr-1">
            {aiSummary && (
              <div className="rounded-md border border-border bg-muted/30 p-2.5">
                <p className="text-[10px] uppercase tracking-wider text-muted-foreground font-semibold mb-1">
                  AI summary
                </p>
                <p className="text-xs text-foreground leading-relaxed whitespace-pre-line">
                  {aiSummary}
                </p>
              </div>
            )}

            {extractedItems.length === 0 ? (
              <p className="text-xs text-muted-foreground italic text-center py-6">
                AI didn't find any field values in the transcript. You can close this and edit the
                checklist manually.
              </p>
            ) : (
              <ul className="space-y-2">
                {extractedItems.map((it) => {
                  const tpl = labelByKey.get(it.key);
                  const existing = rows.find((r) => r.field_key === it.key);
                  const isProtected =
                    existing?.manually_edited ||
                    existing?.status === "approved" ||
                    existing?.status === "review_requested";
                  const checked = acceptedKeys.has(it.key);
                  const confCls =
                    it.confidence === "HIGH"
                      ? "bg-success/15 text-success border-success/30"
                      : it.confidence === "MEDIUM"
                      ? "bg-warning/15 text-warning border-warning/30"
                      : "bg-overdue/15 text-overdue border-overdue/30";
                  return (
                    <li
                      key={it.key}
                      className={`rounded-md border p-2.5 ${
                        isProtected
                          ? "border-warning/40 bg-warning/5"
                          : checked
                          ? "border-teal/40 bg-teal/5"
                          : "border-border bg-card"
                      }`}
                    >
                      <div className="flex items-start gap-2">
                        <Checkbox
                          checked={checked}
                          disabled={isProtected}
                          onCheckedChange={(v) => {
                            setAcceptedKeys((prev) => {
                              const next = new Set(prev);
                              if (v) next.add(it.key);
                              else next.delete(it.key);
                              return next;
                            });
                          }}
                          className="mt-0.5"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="text-xs font-semibold text-foreground">
                              {tpl?.label ?? it.key}
                            </span>
                            <span
                              className={`inline-flex items-center px-1.5 py-0.5 rounded border text-[9px] font-bold uppercase tracking-wider ${confCls}`}
                            >
                              {it.confidence}
                            </span>
                            {isProtected && (
                              <span className="inline-flex items-center gap-1 text-[10px] text-warning">
                                <AlertCircle className="h-3 w-3" /> Will be skipped — protected
                              </span>
                            )}
                          </div>
                          <p className="text-sm text-foreground mt-0.5 break-words">
                            {existing?.value && existing.value !== it.value && (
                              <span className="text-muted-foreground line-through mr-1.5">
                                {existing.value}
                              </span>
                            )}
                            <span className="font-medium">{it.value}</span>
                          </p>
                          {it.evidence_quote && (
                            <p className="text-[10px] text-muted-foreground italic mt-1 leading-relaxed">
                              "{it.evidence_quote}"
                            </p>
                          )}
                        </div>
                      </div>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>

          <div className="flex items-center justify-end gap-2 pt-3 border-t border-border">
            <Button variant="outline" onClick={() => setReviewOpen(false)} disabled={merging}>
              Cancel
            </Button>
            <Button onClick={handleConfirmMerge} disabled={merging || acceptedKeys.size === 0}>
              {merging ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" />
              ) : (
                <CheckCircle2 className="h-3.5 w-3.5 mr-1.5" />
              )}
              Merge {acceptedKeys.size} field{acceptedKeys.size === 1 ? "" : "s"} & save call
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
